services:
  - type: web
    name: cellsense-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_URL
        value: postgresql://postgres:CellSense2026@db.qjhpatciiitdwputpqjk.supabase.co:5432/postgres